export const FETCH_DAPPLETS_START = 'FETCH_DAPPLETS_START';
export const FETCH_DAPPLETS_SUCCESS = 'FETCH_DAPPLETS_SUCCESS';
export const FETCH_DAPPLETS_FAILURE = 'FETCH_DAPPLETS_FAILURE';

export const FETCH_MORE_DAPPLETS_START = 'FETCH_MORE_DAPPLETS_START';
export const FETCH_MORE_DAPPLETS_SUCCESS = 'FETCH_MORE_DAPPLETS_SUCCESS';
export const FETCH_MORE_DAPPLETS_FAILURE = 'FETCH_MORE_DAPPLETS_FAILURE';

export const FETCH_TAGS_START = 'FETCH_TAGS_START';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

export const ON_DRAG_END = 'ON_DRAG_END';
